### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by johnjohndoe**
- Here are a few dependency updates. Please check with your mapbox key.
- Additional:
  - Use [`gradle-versions-plugin`](https://github.com/ben-manes/gradle-versions-plugin) to detect version updates.
  - Allow to install *debug* version in side-by-side with _release_ version.
- Each commit builds.

### CODE REVIEW

**Comment by johnjohndoe** [comment]
Friendly ping :bellhop_bell:

**Comment by dbaelz** [comment]
Hi, sorry for the very (very) late reply. Thanks for the patience. Obviously, the project is no longer maintained.

I will merge the PR in the next days and distribute the version into the Play Store. Afterwards I'll look for another maintainer or archive the project to make the current status more clear.

**Comment by johnjohndoe** [comment]
No worries. It was not urgent. 

I am surprised, though. I find the widgets quite useful to monitor the sensors on my phone. Can you recommend an alternative app?

**Comment by dbaelz** [comment]
Thanks für the PR, I'll tested it and everything seems to work. Will increase the version, build and publish in Google Play soon.

About openSense widgets: I don't know any alternatives, but I'm no longer active with senseBox/openSense anymore. Maybe with the new Android 12 Widgets someone will create a new, much better looking and working, widget. Building widgets with the current API is really tricky. Especially when they should look good. And I know the OpenSense widgets aren't beautiful. :)

**Pull request merged**
